### ISSUE TITLE
Should the shortname for filestore be `file` or `filestore`

### ISSUE THREAD

**Issue by dandhlee** [googleapis/python-filestore#92]
Currently, the shortname for this repository is `file`. This makes the documentation link to `python/docs/reference/file/latest`. It is somewhat inconsistent with the product documentation, which is `cloud.google.com/filestore`. Should we change this on `.repo-metadata.json` to `filestore`, or keep it consistent as `file`?

**Comment by parthea** [comment]
The `api_shortname` should be `file` because the hostname is `file.googleapis.com`. We're taking the part before `.googleapis.com` and using that as the `api_shortname`.
https://github.com/googleapis/googleapis/blob/master/google/cloud/filestore/v1/file_v1.yaml#L3
